//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeCargaDinamico
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionServicio
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int NumeroDePuntos { get; set; }
        public string Region { get; set; }
        public string Direccion { get; set; }
        public string CodigoRegion { get; set; }
    
        public virtual Region Region1 { get; set; }
    }
}
